---
title: "One way ANOVA"
author:
  - name: Hannah Bowley
  - name: Micaela Lembo
format: html
toc: true
editor: visual
theme: lux
---

### Load in Libraries

```{r}
#| echo: true
#| message: false
#| warning: false
library(tidymodels)
library(datarium)
library(gt)
```

### Calculate one way ANOVA using base R

```{r}
## Use AOV function to calculate 
anova <-aov(pain_score ~ treatment, data = headache)

## Tidy ANOVA output and create a gt table 
anova %>% 
  tidy() %>% 
  gt()
```

### Visualize the ANOVA

```{r}
#| echo: true
headache %>% 
  ggplot(aes(treatment, pain_score)) + 
  geom_boxplot()
```

### Calculate the observed statistic 

```{r}
#| echo: true 
## Calculate the observed statistic
observed_f_statistic <- headache %>% 
  specify(pain_score ~ treatment) %>% 
  hypothesize(null = "independence") %>% 
  calculate(stat = "F")

observed_f_statistic
```

### Calculate the Null Distribution Simulation 

```{r}
#| echo: true
## generate the null distribution using randomization

null_distribution <- headache %>% 
  specify(pain_score ~ treatment) %>% 
  hypothesize(null = "independence") %>% 
  generate(reps = 1000, type = "permute") %>% 
  calculate(stat = "F")
```

```{r}
#| echo: true
#| warning: false
#| message: false
null_distribution %>% 
  visualize(method = "both")+
  shade_p_value(observed_f_statistic,
                direction = "greater")
```

### Get the P-Value

```{r}
#| echo: true
## calculate the p-value from the observed statistic

p_value <- null_distribution %>% 
  get_p_value(obs_stat = observed_f_statistic,
              direction = "greater")
p_value %>% 
  gt()
```
